/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PackageMethods;

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}

	public static void main(String[] args) {
		System.out.println(Boolean.toString(new Library().someLibraryMethod()));
	}
}
